CREATE TABLE `Routine` (
  `id` int NOT NULL AUTO_INCREMENT,
  `clientId` varchar(250) NOT NULL,
  `dateTimeBegin` datetime,
  `dateTimeEnd` datetime,
  `monday` bool NOT NULL, 
  `tuesday` bool NOT NULL, 
  `wednesday` bool NOT NULL, 
  `thursday` bool NOT NULL, 
  `friday` bool NOT NULL, 
  `saturday` bool NOT NULL, 
  `saunday` bool NOT NULL, 
  `timeToSend` bool NOT NULL, 
  `status` tinyint(1) NOT NULL DEFAULT '0',
  `sent` tinyint(1) NOT NULL DEFAULT '0',
  `count` decimal,
  `template` varchar(4000) NOT NULL,
  `params` varchar(4000) NOT NULL,
  `update` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2821 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
